# Stage1:
#parameters:
#- name: targetModule
  #default: 'All'
  
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
          target:
            type: choice
            description: 対象環境を選択
            options:
            - dev
            - sqa
            default: dev
            required: true
          tag:
            description: 対象Tag名を指定
            default: ''
            required: true
          isDeployDB:
            description: 'DB'
            required: true
            type: boolean
          isDeployAPI:
            description: 'API'
            required: true
            type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # リソース取得
  UT:        
    # VmImageはWindowsを使う: UT(C#)の実行はWindowsじゃないとダメだから
    runs-on: windows-latest
  
    steps:
        - uses: actions/checkout@v3
        - name: Configure VM1
          run: Set-Timezone -Id "Tokyo Standard Time"
          shell: powershell
        - name: Configure VM2
          run: npm install -g azurite
          shell: powershell
        - name: Configure VM3
          run: Start-Process azurite-blob.cmd -PassThru
          shell: powershell

