# Stage1:
#parameters:
#- name: targetModule
  #default: 'All'
  
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # リソース取得
  UT:        
    # VmImageはWindowsを使う: UT(C#)の実行はWindowsじゃないとダメだから
    runs-on: windows-latest
    #variables:
      #system.debug: true
  
    steps:
      # GitHubからソースをCheckout
      #- checkout: origin
        - uses: actions/checkout@v3
      #- ${{ if or(eq(parameters.targetModule, 'All'), eq(parameters.targetModule, 'Batch'), eq(parameters.targetModule, 'API')) }}:
        - name: Configure VM1
          run: Set-Timezone -Id "Tokyo Standard Time"
          shell: powershell
        - name: Configure VM2
          run: npm install -g azurite
          shell: powershell
        - name: Configure VM3
          run: Start-Process azurite-blob.cmd -PassThru
          shell: powershell
          #inputs:
            #targetType: 'inline'
      #- ${{ if or(eq(parameters.targetModule, 'All'), eq(parameters.targetModule, 'API')) }}:        
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: '4.x'
        - name: Install dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --configuration Release --no-restore
        - name: Test
          run: dotnet test --no-restore --verbosity normal
